//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.15 at 05:34:31 PM EST 
//


package core.fingerprint3;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Return complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Return">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="Details" type="{}DetailGroup"/>
 *         &lt;/choice>
 *         &lt;element ref="{}Extract" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}Direction"/>
 *       &lt;attribute name="Confidence" use="required" type="{}Confidence" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Return", propOrder = {
    "details",
    "extract"
})
public class Return implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Details")
    protected DetailGroup details;
    @XmlElement(name = "Extract")
    protected List<Extract> extract;
    @XmlAttribute(name = "Direction")
    protected Direction direction;
    @XmlAttribute(name = "Confidence", required = true)
    protected int confidence;

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link DetailGroup }
     *     
     */
    public DetailGroup getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailGroup }
     *     
     */
    public void setDetails(DetailGroup value) {
        this.details = value;
    }

    /**
     * Gets the value of the extract property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extract property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtract().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Extract }
     * 
     * 
     */
    public List<Extract> getExtract() {
        if (extract == null) {
            extract = new ArrayList<Extract>();
        }
        return this.extract;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link Direction }
     *     
     */
    public Direction getDirection() {
        if (direction == null) {
            return Direction.SOURCE;
        } else {
            return direction;
        }
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direction }
     *     
     */
    public void setDirection(Direction value) {
        this.direction = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     */
    public int getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     */
    public void setConfidence(int value) {
        this.confidence = value;
    }

}
