package TemplateEngine.Data;

import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Created by BESTDOG on 11/24/2015.
 *
 * Functional interface for the methods generated by the FPC.
 *
 */
@FunctionalInterface
public interface FunctionalOperation<T> {

    void apply(FilterData t, PseudoBuffer payload, Cursor cursor, Consumer<T> ret, Supplier<T> supplier);

}
